/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class olimpicgames_MainFrame_screenType */

#ifndef _Included_olimpicgames_MainFrame_screenType
#define _Included_olimpicgames_MainFrame_screenType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
