/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class olimpicgames_MainFrame */

#ifndef _Included_olimpicgames_MainFrame
#define _Included_olimpicgames_MainFrame
#ifdef __cplusplus
extern "C" {
#endif
#undef olimpicgames_MainFrame_FOCUS_TRAVERSABLE_UNKNOWN
#define olimpicgames_MainFrame_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef olimpicgames_MainFrame_FOCUS_TRAVERSABLE_DEFAULT
#define olimpicgames_MainFrame_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef olimpicgames_MainFrame_FOCUS_TRAVERSABLE_SET
#define olimpicgames_MainFrame_FOCUS_TRAVERSABLE_SET 2L
#undef olimpicgames_MainFrame_TOP_ALIGNMENT
#define olimpicgames_MainFrame_TOP_ALIGNMENT 0.0f
#undef olimpicgames_MainFrame_CENTER_ALIGNMENT
#define olimpicgames_MainFrame_CENTER_ALIGNMENT 0.5f
#undef olimpicgames_MainFrame_BOTTOM_ALIGNMENT
#define olimpicgames_MainFrame_BOTTOM_ALIGNMENT 1.0f
#undef olimpicgames_MainFrame_LEFT_ALIGNMENT
#define olimpicgames_MainFrame_LEFT_ALIGNMENT 0.0f
#undef olimpicgames_MainFrame_RIGHT_ALIGNMENT
#define olimpicgames_MainFrame_RIGHT_ALIGNMENT 1.0f
#undef olimpicgames_MainFrame_serialVersionUID
#define olimpicgames_MainFrame_serialVersionUID -7644114512714619750i64
#undef olimpicgames_MainFrame_serialVersionUID
#define olimpicgames_MainFrame_serialVersionUID 4613797578919906343i64
#undef olimpicgames_MainFrame_INCLUDE_SELF
#define olimpicgames_MainFrame_INCLUDE_SELF 1L
#undef olimpicgames_MainFrame_SEARCH_HEAVYWEIGHTS
#define olimpicgames_MainFrame_SEARCH_HEAVYWEIGHTS 1L
#undef olimpicgames_MainFrame_OPENED
#define olimpicgames_MainFrame_OPENED 1L
#undef olimpicgames_MainFrame_serialVersionUID
#define olimpicgames_MainFrame_serialVersionUID 4497834738069338734i64
#undef olimpicgames_MainFrame_DEFAULT_CURSOR
#define olimpicgames_MainFrame_DEFAULT_CURSOR 0L
#undef olimpicgames_MainFrame_CROSSHAIR_CURSOR
#define olimpicgames_MainFrame_CROSSHAIR_CURSOR 1L
#undef olimpicgames_MainFrame_TEXT_CURSOR
#define olimpicgames_MainFrame_TEXT_CURSOR 2L
#undef olimpicgames_MainFrame_WAIT_CURSOR
#define olimpicgames_MainFrame_WAIT_CURSOR 3L
#undef olimpicgames_MainFrame_SW_RESIZE_CURSOR
#define olimpicgames_MainFrame_SW_RESIZE_CURSOR 4L
#undef olimpicgames_MainFrame_SE_RESIZE_CURSOR
#define olimpicgames_MainFrame_SE_RESIZE_CURSOR 5L
#undef olimpicgames_MainFrame_NW_RESIZE_CURSOR
#define olimpicgames_MainFrame_NW_RESIZE_CURSOR 6L
#undef olimpicgames_MainFrame_NE_RESIZE_CURSOR
#define olimpicgames_MainFrame_NE_RESIZE_CURSOR 7L
#undef olimpicgames_MainFrame_N_RESIZE_CURSOR
#define olimpicgames_MainFrame_N_RESIZE_CURSOR 8L
#undef olimpicgames_MainFrame_S_RESIZE_CURSOR
#define olimpicgames_MainFrame_S_RESIZE_CURSOR 9L
#undef olimpicgames_MainFrame_W_RESIZE_CURSOR
#define olimpicgames_MainFrame_W_RESIZE_CURSOR 10L
#undef olimpicgames_MainFrame_E_RESIZE_CURSOR
#define olimpicgames_MainFrame_E_RESIZE_CURSOR 11L
#undef olimpicgames_MainFrame_HAND_CURSOR
#define olimpicgames_MainFrame_HAND_CURSOR 12L
#undef olimpicgames_MainFrame_MOVE_CURSOR
#define olimpicgames_MainFrame_MOVE_CURSOR 13L
#undef olimpicgames_MainFrame_NORMAL
#define olimpicgames_MainFrame_NORMAL 0L
#undef olimpicgames_MainFrame_ICONIFIED
#define olimpicgames_MainFrame_ICONIFIED 1L
#undef olimpicgames_MainFrame_MAXIMIZED_HORIZ
#define olimpicgames_MainFrame_MAXIMIZED_HORIZ 2L
#undef olimpicgames_MainFrame_MAXIMIZED_VERT
#define olimpicgames_MainFrame_MAXIMIZED_VERT 4L
#undef olimpicgames_MainFrame_MAXIMIZED_BOTH
#define olimpicgames_MainFrame_MAXIMIZED_BOTH 6L
#undef olimpicgames_MainFrame_serialVersionUID
#define olimpicgames_MainFrame_serialVersionUID 2673458971256075116i64
#undef olimpicgames_MainFrame_EXIT_ON_CLOSE
#define olimpicgames_MainFrame_EXIT_ON_CLOSE 3L
/*
 * Class:     olimpicgames_MainFrame
 * Method:    loadFiles
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_olimpicgames_MainFrame_loadFiles
  (JNIEnv *, jobject, jstring);

/*
 * Class:     olimpicgames_MainFrame
 * Method:    getCountries
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_olimpicgames_MainFrame_getCountries
  (JNIEnv *, jobject, jstring);

/*
 * Class:     olimpicgames_MainFrame
 * Method:    getSports
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_olimpicgames_MainFrame_getSports
  (JNIEnv *, jobject, jstring);

/*
 * Class:     olimpicgames_MainFrame
 * Method:    getYears
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_olimpicgames_MainFrame_getYears
  (JNIEnv *, jobject, jstring);

/*
 * Class:     olimpicgames_MainFrame
 * Method:    updateFiles
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_olimpicgames_MainFrame_updateFiles
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     olimpicgames_MainFrame
 * Method:    xyData
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_olimpicgames_MainFrame_xyData
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
